services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_PASSWORD=dev-only
    secrets:
      - server_pass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 5s
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
secrets:
  server_pass:
    external: true